config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'portfolio' => 'static_pages#portfolio'
  get 'experience' => 'static_pages#experience'
  get 'facebook' => 'static_pages#facebook'
  get 'linkedin' => 'static_pages#linkedin'
  get 'resume' => 'static_pages#resume'
  get 'portrait' => 'static_pages#portrait'
  get 'converter' => 'static_pages#converter'

  root 'static_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end

  def terms
  end

  def portfolio
  end

  def experience
  end

  def facebook
  end

  def linkedin
  end

  def resume
  end

  def portrait
  end

  def converter
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_utilities.rb
class ApplicationUtilities
  def self.bin2dec(binary)
    binary.split('').inject(0) { |sum, n| sum = 2 * sum + n.to_i }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <a href="http://www.weichuantian.com" target="_blank">Author: Weichuan Tian</a>
        <div class="HorizLinks">
          <ul>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Terms', terms_path %></li>
          </ul>
        </div>
        <p>Simple Navigation</p>
        <p class="smalltext">Ruby on Rails Assignment 3</p>
      </div>
      <div id="horizontalnav">
        <div class="navlinks">
          <ul>
            <li><%= link_to 'Convert 1001', demo1_path %></li>
            <li><%= link_to 'Convert 101', demo2_path %></li>
            <li><%= link_to 'Convert 11001', demo3_path %></li>
            <li><%= link_to 'Convert 10101010', demo4_path %></li>
          </ul>
        </div>
      </div>
      <div id="leftnav">
        <ul>
          <li><%= link_to 'Facebook', facebook_path %></li>
        </ul>
      </div>
      <div id="rightnav">
        <ul>
          <li><%= link_to 'LinkedIn', linkedIn_path %></li>
        </ul>
      </div>

      <%= yield %>

      <div id="footer">&copy 2016 Weichuan Tian. All Rights Reserved | Simple Navigation</div>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This is my Ruby on Rails Assignment 3.</p>

app/views/static_pages/converter.html.erb
<h1>Binary to Decimal</h1>
<p>Converting 10100100111001 to decimal is: <%= ApplicationUtilities.bin2dec("10100100111001") %></p>

app/views/static_pages/demo1.html.erb
<% provide(:title, "Demo1") %>
<h1>Convert binary to decimal</h1>
<p>Converting 1001 to decimal is: <%= ApplicationUtilities.bin2dec("1001") %></p>

app/views/static_pages/demo2.html.erb
<% provide(:title, "Demo2") %>
<h1>Convert binary to decimal</h1>
<p>Converting 101 to decimal is: <%= ApplicationUtilities.bin2dec("101") %></p>

app/views/static_pages/demo3.html.erb
<% provide(:title, "Demo3") %>
<h1>Convert binary to decimal</h1>
<p>Converting 11001 to decimal is: <%= ApplicationUtilities.bin2dec("11001") %></p>

app/views/static_pages/demo4.html.erb
<% provide(:title, "Demo4") %>
<h1>Convert binary to decimal</h1>
<p>Converting 10101010 to decimal is: <%= ApplicationUtilities.bin2dec("10101010") %></p>

app/views/static_pages/experience.html.erb
<h1>Experience</h1>
<p>app/views/static_pages/experience.html.erb</p>

app/views/static_pages/facebook.html.erb
<% provide(:title, "Facebook") %>
<h1>Facebook</h1>
<p>Please visit me on <%= link_to 'Facebook', 'https://www.facebook.com/weichuan.tian', :target => "_blank" %>!</p>

app/views/static_pages/home.html.erb
<h1>HOME</h1>
<p>Ruby on Rails Assignment 3 - Meng Xie 89552</p>
<p>app/views/static_pages/home.html.erb</p>

app/views/static_pages/linkedIn.html.erb
<% provide(:title, "LinkedIn") %>
<h1>LinkedIn</h1>
<p>Please visit me on <%= link_to 'LinkedIn', 'https://www.linkedin.com/in/weichuan-albert-tian-1010a739', :target => "_blank" %>!</p>

app/views/static_pages/linkedin.html.erb
<h1>Linkedin</h1>
<p>app/views/static_pages/linkedin.html.erb</p>

app/views/static_pages/portfolio.html.erb
<h1>Portfolio</h1>
<p>app/views/static_pages/portfolio.html.erb</p>

app/views/static_pages/portrait.html.erb
<h1>Portrait</h1>
<p>app/views/static_pages/portrait.html.erb</p>

app/views/static_pages/resume.html.erb
<h1>Resume</h1>
<p>app/views/static_pages/resume.html.erb</p>